language: cpp


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: OFBUILD_TRAVIS_BUILDTYPE=debug
    - os: linux
      dist: trusty
      sudo: false
      env: OFBUILD_TRAVIS_BUILDTYPE=release
    - os: osx
      osx_image: xcode9.2

addons:
  apt:
    packages:
    - cmake
    - git
    - gcc
    - g++
    - gfortran
    - libboost-dev
    - libboost-test-dev
    - qt5-default
    - qtbase5-dev
    - qtbase5-dev-tools
    - qttools5-dev
    - qttools5-dev-tools
    - libqt5svg5-dev
    - libgdal1h 
    - libgdal1-dev 
    - libgeos++-dev 
    - p7zip-full 
    - gnuplot 
    - graphviz


install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ] ; then brew install qt rapidjson doxygen ; fi

before_script:
  - echo "SET(OPENFLUID_ENABLE_MARKET 1)" > CMake.in.local.cmake
  - echo "SET(OFBUILD_TESTS_ENABLE_FORTRAN 1)" >> CMake.in.local.cmake  
  - echo "SET(OFBUILD_UNITTESTS_RUN_OPTIONS \"--log_level=all\")" >> CMake.in.local.cmake
  - echo "SET(OFBUILD_TESTS_GITHELPER_AUTH_URL \"\")" >> CMake.in.local.cmake
  - mkdir _build
  - cd _build
  - if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "debug" ] ; then cmake .. -DOPENFLUID_ENABLE_HEAVYTESTING=1 ; fi
  - if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "release" ] ; then cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ] ; then cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.10.0_1/lib/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ; fi 
  
script:
  - if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "debug" ] ; then make && ctest --output-on-failure ; fi
  - if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "release" ] ; then make && cpack ; fi  
  - if [ "${TRAVIS_OS_NAME}" == "osx" ] ; then make && cmake -P ofpack-osx-brewcask.cmake ; fi


notifications:
  email:
    on_success: always
    on_failure: always

